### ISSUE TITLE
Alignment out with 6 rows in table axes

### ISSUE THREAD

**Issue by johanndt** [sandialabs/toyplot#141] opened 2016-02-18 06:06 UTC
Hi,

This is a weird one and I can't figure it out.

I have a table, and the last column of the table has a bar graph to indicate some value. Everything is fine and the text in each row lines up perfectly with the bar in the last column.

EXCEPT when I have 6 rows in the table.

It looks fine with 5 and 7. I've added some Jupyter gists so you can see what I mean.

Here is the misaligned bars with 6 rows:
https://gist.github.com/johanndt/de3debde4a027915a5d4

And here is a proper one of how I should expect the bars to line up with 5:
https://gist.github.com/johanndt/b42cf7190e914b8df515

Or with 7 it works too:
https://gist.github.com/johanndt/97a74ac2f51ce932fd3d

I'm at a bit of a loss. Would love to get some feedback or a workaround please.
Johann

**Comment by tshead2** [comment] 2016-02-18 16:25
@johanndt : This is a duplicate of #134 ... in a nutshell, the tick locator for the plot is adjusting the y-axis domain so it can display "nice" tick labels, even though the ticks are hidden.  Fortunately, there are multiple workarounds:

* Explicitly hide the y-axis with `axes.y.show = False`
* Switch to a tick locator that won't adjust the domain, for example `axes.y.ticks.locator = toyplot.locator.Null()`
* Switch to master, where the bug is fixed.

In addition, I will look at getting Toyplot 0.11.0 out either later today or tomorrow, which will have this fix.

Thanks for the heads-up!
Tim

**Comment by tshead2** [comment] 2016-02-18 17:46
OK, Toyplot 0.11.0 is officially out, and includes the fix for #134.

**Closed by tshead2** 2016-02-18 17:46 UTC
Labels: Bug, Duplicate
