### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by zhuoqiang** [sandialabs/toyplot#55] opened 2015-07-08 05:59 UTC
while toyplot could be installed and run under python3, however, the inline graphic did not show up in python3 ipython notebook session. The following warning message might be helpful:

``lib/python3.4/site-packages/IPython/core/formatters.py:360: FormatterWarning: text/html formatter returned invalid type <class 'bytes'> (expected (<class 'str'>,)) for object: <toyplot.canvas.Canvas object at 0x10741eef0>
  FormatterWarning 
``

**Comment by tshead** [comment] 2015-07-08 06:26
@zhuoqiang : This may be a duplicate of #50, which was fixed earlier today.  Any chance you could try the current master from Github and see if it solves the problem for you?

Many thanks,
Tim

**Comment by zhuoqiang** [comment] 2015-07-08 07:06
@tshead: Just tried the latest code from github, works perfect on python3 ipython notebook. Thanks for the quick fix.

**Comment by tshead2** [comment] 2015-07-08 15:00
Glad it worked for you!  I'll probably have a new release out in PyPi in the next week-or-so.

**Closed by tshead2** 2015-07-08 15:00 UTC
