### ISSUE TITLE
Canvas does not display in Jupyter notebook in Python 3.4

### ISSUE THREAD

**Issue by PeterSulcs** [sandialabs/toyplot#61] opened 2015-07-13 13:20 UTC
Tried tutorial for version 0.5.0 in a jupyter notebook:
```python
import toyplot
import numpy as np
x = np.linspace(0, 10)
y = x ** 2
canvas = toyplot.Canvas(width=300, height=300)
axes = canvas.axes()
mark = axes.plot(x, y)
```

And get:
```
[USERPATH]\envs\anapy3\lib\site-packages\IPython\core\formatters.py:360: FormatterWarning: text/html formatter returned invalid type <class 'bytes'> (expected (<class 'str'>,)) for object: <toyplot.canvas.Canvas object at 0x0000000005C3EF28>
  FormatterWarning
<toyplot.canvas.Canvas at 0x5c3ef28>
```
and no plot.

Environment:
```
# packages in environment at [USERPATH]\envs\anapy3:
#
_license                  1.1                      py34_0  
alabaster                 0.7.3                    py34_0  
anaconda                  2.3.0                np19py34_0  
argcomplete               0.8.9                    py34_0  
astropy                   1.0.3                np19py34_0  
babel                     1.3                      py34_0  
bcolz                     0.9.0                np19py34_0  
beautiful-soup            4.3.2                    py34_1  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py34_0  
bitarray                  0.8.1                    py34_1  
blaze                     0.7.3                np19py34_0  
blaze-core                0.8.0                np19py34_0  
blist                     1.3.6                    py34_0  
blz                       0.6.2                np19py34_1  
bokeh                     0.9.0                np19py34_0  
boto                      2.38.0                   py34_0  
bottleneck                1.0.0                np19py34_0  
cassandra-driver          2.1.3                     <pip>
certifi                   14.05.14                 py34_0  
cffi                      1.1.0                    py34_0  
clyent                    0.3.4                    py34_0  
colorama                  0.3.3                    py34_0  
colormath                 2.1.1                     <pip>
configobj                 5.0.6                    py34_0  
cryptography              0.9.1                    py34_0  
cython                    0.22.1                   py34_0  
cytoolz                   0.7.3                    py34_0  
datashape                 0.4.5                np19py34_0  
dateutil                  2.1                      py34_2  
decorator                 3.4.2                    py34_0  
docopt                    0.6.2                     <pip>
docutils                  0.12                     py34_1  
dynd-python               0.6.5                np19py34_0  
fastcache                 1.0.2                    py34_0  
flask                     0.10.1                   py34_1  
future                    0.13.1                   py34_0  
futures                   2.2.0                     <pip>
greenlet                  0.4.7                    py34_0  
h5py                      2.5.0                np19py34_1  
hdf5                      1.8.15.1                      2  
idna                      2.0                      py34_0  
ipython                   3.2.0                    py34_0  
ipython-notebook          3.2.0                    py34_0  
ipython-qtconsole         3.2.0                    py34_0  
itsdangerous              0.24                     py34_0  
jdcal                     1.0                      py34_0  
jedi                      0.8.1                    py34_0  
jinja2                    2.7.3                    py34_2  
jsonschema                2.4.0                    py34_0  
launcher                  1.0.0                         1  
libpython                 1.0                      py34_1  
llvmlite                  0.5.0                    py34_0  
llvmpy                    0.12.7                   py34_0  
lxml                      3.4.4                    py34_0  
markdown2                 2.3.0                     <pip>
markupsafe                0.23                     py34_0  
matplotlib                1.4.3                np19py34_1  
menuinst                  1.0.4                    py34_0  
mingw                     4.7                           1  
mistune                   0.5.1                    py34_1  
mock                      1.0.1                    py34_0  
multipledispatch          0.4.7                    py34_0  
networkx                  1.9.1                    py34_0  
nltk                      3.0.3                np19py34_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py34_0  
numba                     0.19.1               np19py34_0  
numexpr                   2.4.3                np19py34_0  
numpy                     1.9.2                    py34_0  
odo                       0.3.2                np19py34_0  
openpyxl                  1.8.5                    py34_0  
pandas                    0.16.2               np19py34_0  
patsy                     0.3.0                np19py34_0  
pep8                      1.6.2                    py34_0  
pillow                    2.8.2                    py34_0  
pip                       7.1.0                    py34_0  
ply                       3.6                      py34_0  
psutil                    2.2.1                    py34_0  
py                        1.4.27                   py34_0  
pyasn1                    0.1.7                    py34_0  
pycosat                   0.6.1                    py34_0  
pycparser                 2.14                     py34_0  
pycrypto                  2.6.1                    py34_3  
pyflakes                  0.9.2                    py34_0  
pygments                  2.0.2                    py34_0  
pymongo                   2.8                      py34_0  
pyopenssl                 0.15.1                   py34_1  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.10.4                   py34_1  
pyreadline                2.0                      py34_0  
pytables                  3.2.0                np19py34_0  
pytest                    2.7.1                    py34_0  
python                    3.4.3                         0  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.4                   py34_0  
pywin32                   219                      py34_0  
pyyaml                    3.11                     py34_1  
pyzmq                     14.7.0                   py34_0  
requests                  2.7.0                    py34_0  
rodeo                     0.2.4                     <pip>
rope                      0.9.4                    py34_1  
rope-py3k-0.9.4           1                         <pip>
runipy                    0.1.3                    py34_0  
scikit-image              0.11.3               np19py34_0  
scikit-learn              0.16.1               np19py34_0  
scipy                     0.15.1               np19py34_0  
seaborn                   0.6.0                np19py34_0  
setuptools                18.0.1                   py34_0  
six                       1.9.0                    py34_0  
snowballstemmer           1.2.0                    py34_0  
sockjs-tornado            1.0.1                    py34_0  
sphinx                    1.3.1                    py34_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0  
spyder                    2.3.5.2                  py34_0  
spyder-app                2.3.5.2                  py34_0  
sqlalchemy                1.0.5                    py34_0  
statsmodels               0.6.1                np19py34_0  
sympy                     0.7.6                    py34_0  
tables                    3.2.0                     <pip>
toolz                     0.7.2                    py34_0  
tornado                   4.2                      py34_0  
toyplot                   0.5.0                     <pip>
ujson                     1.33                     py34_0  
werkzeug                  0.10.4                   py34_0  
xlrd                      0.9.3                    py34_0  
xlsxwriter                0.7.3                    py34_0  
xlwings                   0.3.5                    py34_0  
xlwt                      1.0.0                    py34_0  
zlib                      1.2.8                         0  
```

**Comment by tshead2** [comment] 2015-07-13 14:53
@PeterSulcs - pretty confident that this is a duplicate of #50, which was fixed a couple of days ago.  You can try pulling master from github, or wait a couple of days for the 0.6.0 release, which will include this fix.  Many thanks!  Tim

**Closed** 2015-07-13 15:07 UTC
Labels: bug, duplicate

**Comment by tshead2** [comment] 2015-07-14 16:52
@PeterSulcs - a heads-up that Toyplot 0.6.0 was just released, with a fix for this issue.

**Comment by PeterSulcs** [comment] 2015-07-16 14:06
@tshead2 - Thanks, I'll check it out!
